sources:
  - name: Shop
    handler:
      graphql:
        endpoint: http://localhost:8084/graphql/
        method: POST
  - name: PromotionManagement
    handler:
      graphql:
        endpoint: http://localhost:8085/graphql/
        method: POST
  - name: SandwichM
    handler:
      graphql:
        endpoint: http://localhost:52456/graphql/
        method: POST
  - name: OrderManagement
    handler:
      graphql:
        endpoint: http://localhost:8082/graphql/
        method: POST
serve:
  endpoint: /graphql  
plugins:
  - rateLimit:
      config:
        # Add as many rules as you want
        - type: Query
          field: foo
          max: 5 # requests limit for a time period
          ttl: 5000 # time period
          identifier: '{context.userId}'    