// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sandwich.Entities.Context;

#nullable disable

namespace Sandwich.Migrations
{
    [DbContext(typeof(SandwichDbContext))]
    [Migration("20221223011953_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Sandwich.Entities.Entity.Sandwiches", b =>
                {
                    b.Property<int>("SandwichId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SandwichDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("SandwichDesignation")
                        .HasColumnType("longtext");

                    b.Property<string>("SandwichPrice")
                        .HasColumnType("longtext");

                    b.HasKey("SandwichId");

                    b.ToTable("Sandwiches");
                });
#pragma warning restore 612, 618
        }
    }
}
